### PR TITLE
Enforce permissions of config files

### PR DESCRIPTION
**Pull request by tenyo**
Addresses #18

### CODE REVIEW

**Comment by fishnix** [comment]
@tenyo thanks, can you also add an optional `sensitive` to the file resources for those config files so they don't end up in the log?  I'd like that to be false by default since I personally like to see the data and don't have secrets yet.  We should also update the integration tests to look for these permissions:  https://github.com/NorthPage/telegraf-cookbook/blob/master/test/integration/default/serverspec/default_spec.rb

**Comment by tenyo** [comment]
Good idea to have a sensitive property - I made it to also control the mode - this way people can override as needed per input/output, and by default they'll be world readable.

**Comment by fishnix** [comment]
Changes in 06f2a022b412132fadb6cc59cbe79d1f926d7ab1 look good, I haven't had a chance to run kitchen yet.  Assuming you have, :+1: Thanks!

**Comment by tenyo** [comment]
Yup, all tested.

**Pull request merged**
