### PR TITLE
switching from toml-rb to toml gem

### PR DESCRIPTION
**Pull request by codylewandowski**
This is a potential replacement to #39 and a fix to #41.  I tested this in combination with the latest version of https://github.com/bdangit/chef-influxdb and everything worked as expected.

### CODE REVIEW

**Comment by codylewandowski** [comment]
@fishnix @phromo Does this better align with the issues that you commend in #39?

**Comment by fishnix** [comment]
thanks @codylewandowski, reviewing this now

**Comment by fishnix** [comment]
Looks good, thanks again! 👍

**Comment by codylewandowski** [comment]
Thanks for the quick release too @fishnix! You rock!

**Comment by joshmyers** [comment]
Hi @fishnix @codylewandowski this commit seems to break existing behaviour when generating TOML from a ruby hash:

Given a ruby hash example:

```ruby
foo = {
  "cpu" => {
    'percpu'    => true,
    'totalcpu'  => true,
    'fielddrop' => [ 'time_*' ]
  },
  "disk" =>  {
    'ignore_fs' => [ "tmpfs", "devtmpfs" ],
    'tagexclude' => ['fstype', 'path', 'device']
  },
  "diskio" => {},
  "mem"    => {},
  "net"    => {},
  "swap"   => {},
  "system" => {}
}
```

Expected output (when using toml-rb):

```
puts TomlRB.dump(foo)
[cpu]
fielddrop = ["time_*"]
percpu = true
totalcpu = true
[disk]
ignore_fs = ["tmpfs", "devtmpfs"]
tagexclude = ["fstype", "path", "device"]
[diskio]
[mem]
[net]
[swap]
[system]
```

Actual output (now using toml):

```
puts TOML::Generator.new(foo).body

[cpu]
fielddrop = ["time_*"]
percpu = true
totalcpu = true

[disk]
ignore_fs = ["tmpfs","devtmpfs"]
tagexclude = ["fstype","path","device"]
```

As can be seen above empty hash keys result in no Telegraf config.

Do you want me to open an issue against this?

**Comment by lindwaltz** [comment]
please see https://github.com/phromo/telegraf-cookbook/commit/17bb8b6d674db23c7e89a74ea677ac5b0948789b for a fix. Sorry for not replying to this issue. Had a daughter, not much free time atm :)

**Comment by phromo** [comment]
sorry for not replying to earlier PR. I fixed the issue @joshmyers refers to in https://github.com/phromo/telegraf-cookbook/commit/17bb8b6d674db23c7e89a74ea677ac5b0948789b 

I've just become a father to a lovely daughter and don't have much time for computers atm :)

**Comment by jrg72** [comment]
Thank you @phromo, your fix in that fork of yours was the solution to a non-work-hours upgrade failure for our telegraf wrapper cookbook in prod! 

Though, it looks like this is still broken in master here, given that  the defaults in the attributes file still defaults to => {}.

**Comment by codylewandowski** [comment]
@joshmyers @phromo @jrg72 I just opened #46 to address these issues.  Sorry for the delay in response!

**Pull request merged**
