### PR TITLE
Add Mac OS X install support

### PR DESCRIPTION
**Pull request by Sauraus**

### CODE REVIEW

**Comment by fishnix** [comment]
Thanks for the PR!  I haven't had a chance to test this yet, but out of the box there is no package system for OSX, so shouldn't you be adding a dependency for that?  (ie.`chocolatey` for windows)

**Comment by Plork** [comment]
maybe https://github.com/chef-cookbooks/homebrew?

**Comment by Sauraus** [comment]
I will get this sorted asap, sorry for the delay.

Chef is a bit of a PITA on OSX, the default package manager with chef is `homebrew` however you must install it yourself before you can use it.

**Comment by Sauraus** [comment]
`homebrew` dependency issue resolved.

**Comment by fishnix** [comment]
Thanks looks good, can you add it to the README and I'll merge it up? 👍 

*edit:* I'll take care of this.  Thanks for the PR!

**Pull request merged**
