### PR TITLE
Fix Toml module

### PR DESCRIPTION
**Pull request by alaa**

### CODE REVIEW

**Comment by phromo** [comment]
+1. rationale: influxdb-cookbook switched to the 'toml' gem, saying in their PR that chef 13 depends on inspec which depends on the toml gem.

See https://github.com/bdangit/chef-influxdb/pull/143

**Comment by phromo** [comment]
tho, I guess the PR should be fixed so that it does not regress ['telegraf']['rubysource'] and works with a config-only recipe. ping if you want me to fix it for you alaa.

**Comment by fishnix** [comment]
That `toml` gem issue has been a problem in the past.  It looks like you guys are working on this, ping me once it's complete and the conflicts are resolved so I can review.  Thanks for the PR!

**Comment by codylewandowski** [comment]
Is there any idea when this PR will be ready to go? As of today, we're now unable to use this cookbook based on the issues outlined in #41. This PR would theoretically resolve those issues.

**Comment by fishnix** [comment]
@codylewandowski @phromo @alaa I'm happy to merge this up once it gets fixed (or also happy to merge a new PR and close this one if that's easier).

**Comment by codylewandowski** [comment]
@fishnix Thanks! I should be able to open a new PR relatively quickly.

**Comment by fishnix** [comment]
closing this out in favor of https://github.com/NorthPage/telegraf-cookbook/pull/43.  Thanks!

**Pull request closed without merging**
