### PR TITLE
fixing default inputs to include default system metrics

### PR DESCRIPTION
**Pull request by codylewandowski**
Fixing broken default inputs introduced by #43 and brought up by @joshmyers and @phromo. 

I also pulled in the tests introduced in #44 by @petre so that I could ensure these changes fully worked. I can remove these if you would prefer to merge them as two PRs.

### CODE REVIEW

**Comment by codylewandowski** [comment]
@fishnix Could you review this when you have a chance?

**Comment by lindwaltz** [comment]
imho: pull this and then think about whether to go back to toml-rb now that the namespace issue is resolved (https://github.com/emancu/toml-rb/issues/99) =)

**Comment by codylewandowski** [comment]
@lindwaltz I can certainly look at moving back to the toml-rb gem, though part of the rational for the move to this gem was that the influx cookbook also switched to it.

**Comment by lindwaltz** [comment]
yeah, but the namespace issue was what forced influx to move, which forced telegraf-cookbook to move.

looking at the source code of the respective gems, I'd fairly guess that most people would prefer toml-rb.

**Comment by codylewandowski** [comment]
@lindwaltz I'll try using the toml-rb gem locally and see if there are any breaking changes that were introduced.

**Comment by codylewandowski** [comment]
The renamed toml-rb gem now works again. I tested the result if anyone fixed the current issue by wrapping the hashes in arrays and the input file still rendered correctly. I also tested this in conjunction with the influx cookbook using the toml gem and that worked as well. I think I'd agree that using the toml-rb gem is a simpler and more elegant solution. I'll open up a PR soon to move back to the other gem 😃

**Pull request closed without merging**
